Feat/password: Add password check on python side before passing to node for unlock
Kings-Distributed-Systems/Bifrost pull request #116
Opened 2023-10-25 15:43 UTC by Hamada-Distributed

This PR adds the capability for a user to be prompted for a passphrase. Note that a user will always be prompted even if the keystore given is passphraseless unless they specify the `keystore_unlocked=True` in `job.exec`.

2023-10-25 18:52 UTC, wiwichips commented
At first glance everything looks good! 
```python
import time
import numpy as np
from bifrost import dcp

# INPUT SET
input_set = list("\"Un bon MOT ne prouve rien.\"")

# WORK FUNCTION
def work_function(character):
  return character.upper()

# COMPUTE_FOR
job = dcp.compute_for(input_set, work_function)

# EXEC
result_set = job.exec(keystore_unlocked=True)

# DISPLAY RESULTS
print(''.join(result_set))\
```

properly deploys a job for a bank acct keystore that has an empty string password

---

stlll looking into it

2023-10-25 19:16 UTC, wiwichips requested changes
Some notes / nitpicks. Not sure how important they are, feel free to dismiss them and I'll consider the MR good to go:

---

Is it expected for this code `job["payment_account_password"]="123123"` to result in the following error:
  - ```TypeError: Job.__setitem__() takes 2 positional arguments but 3 were given```

Not sure hows bifrost 1 handles dot vs key access for dict like objects - PythonMonkey conflates them which is maybe weirder. But I was also surprised to see this error

---
How do you set the password for a keystore whose password isn't the empty string? Or is that out of the scope of this mr. The following code doesn't work (I think as expected since the keystore is never unlocked?)

```python
import time
import numpy as np
from bifrost import dcp

# INPUT SET
input_set = list("\"Un bon MOT ne prouve rien.\"")

# WORK FUNCTION
def work_function(character):
  return character.upper()

# COMPUTE_FOR
job = dcp.compute_for(input_set, work_function)

# SET PASSWORD
job.payment_account_password="123123"

# EXEC
result_set = job.exec(keystore_unlocked=True)

# DISPLAY RESULTS
print(''.join(result_set))
```

I get the following output:
```
State : exec
Passphrase prompt may be hidden because stdout is not tty.
```
It gets stuck and never deploys. If I try to type the password it doesn't take it in

2023-10-25 20:17 UTC, Hamada-Distributed commented
> Is it expected for this code `job["payment_account_password"]="123123"` to result in the following error:
> * `TypeError: Job.__setitem__() takes 2 positional arguments but 3 were given`

yes. You are not expected to set the payment_account_password manually or by code.

> How do you set the password for a keystore whose password isn't the empty string? Or is that out of the scope of this mr. The following code doesn't work (I think as expected since the keystore is never unlocked?)
> 
> ```python
> import time
> import numpy as np
> from bifrost import dcp
> 
> # INPUT SET
> input_set = list("\"Un bon MOT ne prouve rien.\"")
> 
> # WORK FUNCTION
> def work_function(character):
>   return character.upper()
> 
> # COMPUTE_FOR
> job = dcp.compute_for(input_set, work_function)
> 
> # SET PASSWORD
> job.payment_account_password="123123"
> 
> # EXEC
> result_set = job.exec(keystore_unlocked=True)
> 
> # DISPLAY RESULTS
> print(''.join(result_set))
> ```

You should never set the password in plaintext on the job. Instead, try the following:
```
import time
import numpy as np
from bifrost import dcp
import json
 
# INPUT SET
input_set = list("\"Un bon MOT ne prouve rien.\"")

# WORK FUNCTION
def work_function(character):
  return character.upper()

# COMPUTE_FOR
job = dcp.compute_for(input_set, work_function)

#Load the keystore as a string
with open('PATH_TO_KEYSTORE', 'r') as f:
  account = json.load(f)

# EXEC
result_set = job.exec(payment_account = account )

# DISPLAY RESULTS
print(''.join(result_set))
```

You'll automatically be asked for the password.

2023-10-26 11:45 UTC, wiwichips approved these changes
Awesome LGTM!

2023-10-26 14:03 UTC, merged